1. Write a Python Program to Add Two Matrices?


In [11]:
import numpy as np
try:
  A = np.array([[2, 4], [5, -6]])
  B = np.array([[9, -3], [3, 6]])
  C = A + B  
  print("A=",A)  
  print("B=", B)  
  print("C=A+B=")
  print(C)
except:
  print(" both matrix dont have same rows and column")

A= [[ 2  4]
 [ 5 -6]]
B= [[ 9 -3]
 [ 3  6]]
C=A+B=
[[11  1]
 [ 8  0]]


In [20]:
k=eval(input())
k
print(k)
type(k)

[[2, 4], [5, -6]]
[[2, 4], [5, -6]]


list

2. Write a Python Program to Multiply Two Matrices?


In [27]:
import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


3. Write a Python Program to Transpose a Matrix?


In [15]:
import numpy as np
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]


4. Write a Python Program to Sort Words in Alphabetic Order?


In [23]:
def sortword():
    k = input("Enter a String: ")
    sorted_list = sorted(k.split(' '))
    print(' '.join(sorted_list))

sortword()

Enter a String: my name is suman
is my name suman


5. Write a Python Program to Remove Punctuation From a String?

In [ ]:
def removePunctuatuions():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    k = input('Enter a String: ')
    m = ''
    for ele in k:
        if ele not in punctuations:
            m += ele
    print(m)

In [25]:
removePunctuatuions()


Enter a String: my name is suman . what's ur name?
my name is suman  whats ur name
